FROM  gcr.io/istio-testing/build-tools-proxy@sha256:ef91d7f32369c5663b650cc645adf6da06bb94fcb3a0bfdd6cef43e5cfc669e0 AS releasebuilder
RUN apt-get update -y && apt-get install -y emacs less
RUN mkdir /proxy
RUN mkdir /envoy

COPY buildtools/proxybuilder_buildscript.sh /build.sh

CMD ["/bin/bash"]
# Now, just run bash on it and try to build from the resulting commandline