version: 2

jobs:
  build:
    docker:
      - image: istio/ci:go1.10-bazel0.15-clang6.0
    environment:
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux_fastbuild-bazel-cache-{{ checksum "WORKSPACE" }}
      # To build docker containers or run tests in a docker
      - setup_remote_docker
      - run: rm ~/.gitconfig
      - run: make check
      - run: make deb
      - run: make test
      - save_cache:
          key: linux_fastbuild-bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.cache/bazel
      - store_artifacts:
          path: /home/circleci/project/bazel-bin/tools/deb/istio-proxy.deb
          destination: /proxy/deb
      - store_artifacts:
          path: /home/circleci/project/bazel-bin/src/envoy/envoy
          destination: /proxy/bin
  linux_asan:
    docker:
      - image: istio/ci:go1.10-bazel0.15-clang6.0
    environment:
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux_asan-bazel-cache-{{ checksum "WORKSPACE" }}
      # To build docker containers or run tests in a docker
      - setup_remote_docker
      - run: rm ~/.gitconfig
      - run: make test_asan
      - save_cache:
          key: linux_asan-bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.cache/bazel
  linux_tsan:
    docker:
      - image: istio/ci:go1.10-bazel0.15-clang6.0
    environment:
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux_tsan-bazel-cache-{{ checksum "WORKSPACE" }}
      # To build docker containers or run tests in a docker
      - setup_remote_docker
      - run: rm ~/.gitconfig
      - run: make test_tsan
      - save_cache:
          key: linux_tsan-bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.cache/bazel
  macos:
    macos:
      xcode: "9.3.0"
    environment:
      - BAZEL_STARTUP_ARGS: "--output_base /Users/distiller/.cache/bazel"
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
      - CC: clang
      - CXX: clang++
    steps:
      - run: sudo ntpdate -vu time.apple.com
      - run: brew install bazel cmake coreutils go libtool ninja wget
      - run: sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
      - checkout
      - restore_cache:
          keys:
            - macos_fastbuild_v2-bazel-cache-{{ checksum "WORKSPACE" }}
      - run: rm ~/.gitconfig
      - run: make build_envoy
      - run: make test
      - save_cache:
          key: macos_fastbuild_v2-bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /Users/distiller/.cache/bazel

workflows:
  version: 2
  all:
    jobs:
      - build
      - linux_asan
      - linux_tsan
      - macos
