version: 2

jobs:
  build:
    docker:
      - image: istio/ci:go1.9-bazel0.11
    environment:
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}
      - restore_cache:
          keys:
            - repo-cache-{{ checksum "WORKSPACE" }}
      # To build docker containers or run tests in a docker
      - setup_remote_docker
      - run: rm ~/.gitconfig
      - run: make check
      - run: make deb BAZEL_BUILD_ARGS="-j 4"
      - run: make test
      - run: make test_asan
      - run: make test_tsan
      - save_cache:
          key: repo-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.repo
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.cache/bazel
      - store_artifacts:
          path: /home/circleci/project/bazel-bin/tools/deb/istio-proxy.deb
          destination: /proxy/deb
      - store_artifacts:
          path: /home/circleci/project/bazel-bin/src/envoy/mixer/envoy
          destination: /proxy/bin
  macos:
    macos:
      xcode: "9.3.0"
    environment:
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
    steps:
      - run: sudo ntpdate -vu time.apple.com
      - run: brew install automake bazel cmake coreutils go libtool wget
      - checkout
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}-macos
      - run: rm ~/.gitconfig
      - run: make test
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}-macos
          paths:
            - /home/circleci/.cache/bazel

workflows:
  version: 2
  all:
    jobs:
      - build
      - macos
